POST http://localhost:3001/api/tareas/post HTTP/1.1
Content-Type: application/json

{
    "contenido": "intento desde extensión rest client exitoso" 
}

###
POST http://localhost:3001/api/stock/post HTTP/1.1
Content-Type: application/json

{
    "producto": "Salchichas",
    "cantidad": 6
}
